import { ServiceCategory, ServiceItem, CategoryMeta } from './types';
import { Shield, Smartphone, Gamepad2, Briefcase } from 'lucide-react';

export const TRANSLATIONS = {
  en: {
    searchPlaceholder: "Search services...",
    searchCategoryPlaceholder: "Search in this category...",
    searchAll: "Search all services...",
    filters: "Filters",
    sortBy: "Sort By",
    priceRange: "Price Range",
    searchScope: "Search Scope",
    searchAllCategories: "Search All Categories",
    heroTitle: "Welcome to ATLASVAULT",
    heroSubtitle: "Premium Digital Services",
    heroDesc: "Discover elite solutions tailored for the modern digital lifestyle. From secure storage to global connectivity and gaming dominance, we curate the best for you.",
    browseCatalog: "Browse Catalog",
    viewAll: "View All",
    noServices: "No services found matching your criteria.",
    startOrder: "Start Your Order",
    email: "Email Address",
    phone: "Phone Number",
    details: "Required Identifier / Details",
    orderWhatsApp: "Order via WhatsApp",
    similarServices: "Similar Services",
    home: "Home",
    myOrders: "My Orders",
    contactSales: "Contact Sales",
    customSolutions: "Custom Solutions?",
    customSolutionsDesc: "Contact sales for enterprise packages.",
    adminConsole: "Admin Console",
    serviceCatalog: "Service Catalog",
    dashboard: "Dashboard",
    catalogServices: "Catalog Services",
    orders: "Orders",
    userDirectory: "User Directory",
    exitAdmin: "Exit Admin Mode",
    switchToAdmin: "Switch to Admin",
    management: "Management",
    main: "Main",
    categories: "Categories",
    welcomeBack: "Welcome Back",
    access: "Access",
    logOut: "Log Out",
    enterEmail: "Enter your email address to access your order dashboard.",
    noOrders: "No Orders Found",
    description: "Description",
    conditions: "Conditions",
    requirements: "Requirements",
    pricePerUnit: "per unit",
    active: "Active",
    inactive: "Inactive",
    price: "Price",
    service: "Service",
    customer: "Customer",
    status: "Status",
    date: "Date",
    actions: "Actions",
    newest: "Newest Arrivals",
    popularity: "Popularity",
    nameAz: "Name: A - Z",
    globalSearch: "Global Search Results",
    searchResults: "Search Results",
    searching: "Searching",
    showingResults: "Showing results for",
    tryAdjusting: "Try adjusting your filters or search query.",
    login: "Log In",
    register: "Register",
    password: "Password",
    name: "Full Name",
    confirmPassword: "Confirm Password",
    alreadyAccount: "Already have an account?",
    noAccount: "Don't have an account?",
    profile: "Profile",
    updateProfile: "Update Profile",
    loginToAccess: "Log in to access account features",
    guestMode: "Guest Mode",
    admin: "Admin",
    user: "User",
    accountType: "Account Type",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    invalidCredentials: "Invalid email or password",
    emailExists: "Email already registered",
    passwordsDoNotMatch: "Passwords do not match",
    accountCreated: "Account created successfully",
    loginSuccess: "Logged in successfully",
    profileUpdated: "Profile updated successfully",
    role: "Role",
    reviews: "Reviews",
    writeReview: "Write a Review",
    rating: "Rating",
    comment: "Comment",
    submitReview: "Submit Review",
    noReviews: "No reviews yet. Be the first to review!",
    loginToReview: "Please log in to leave a review.",
    favorites: "Favorites",
    myFavorites: "My Favorites",
    reviewAdded: "Review submitted successfully",
    loginGoogle: "Continue with Google",
    or: "or",
    settings: "Settings",
    general: "General",
    appearance: "Appearance",
    language: "Language",
    account: "Account",
    notifications: "Notifications",
    security: "Security",
    about: "About",
    themeLight: "Light",
    themeDark: "Dark",
    enableNotifs: "Enable Notifications",
    marketing: "Marketing Emails",
    appVersion: "App Version",
    themeDesc: "Customize the look and feel",
    langDesc: "Choose your preferred language",
    notifDesc: "Manage your communication preferences"
  },
  fr: {
    searchPlaceholder: "Rechercher...",
    searchCategoryPlaceholder: "Rechercher dans cette catégorie...",
    searchAll: "Rechercher partout...",
    filters: "Filtres",
    sortBy: "Trier par",
    priceRange: "Fourchette de prix",
    searchScope: "Portée",
    searchAllCategories: "Toutes catégories",
    heroTitle: "Bienvenue sur ATLASVAULT",
    heroSubtitle: "Services Numériques Premium",
    heroDesc: "Découvrez des solutions d'élite pour votre style de vie numérique. Du stockage sécurisé à la connectivité mondiale et au gaming, nous sélectionnons le meilleur pour vous.",
    browseCatalog: "Voir le Catalogue",
    viewAll: "Voir tout",
    noServices: "Aucun service trouvé correspondant à vos critères.",
    startOrder: "Commencer la Commande",
    email: "Adresse Email",
    phone: "Numéro de Téléphone",
    details: "Détails / Identifiant Requis",
    orderWhatsApp: "Commander via WhatsApp",
    similarServices: "Services Similaires",
    home: "Accueil",
    myOrders: "Mes Commandes",
    contactSales: "Contacter Ventes",
    customSolutions: "Solutions Sur Mesure ?",
    customSolutionsDesc: "Contactez les ventes pour les offres entreprise.",
    adminConsole: "Console Admin",
    serviceCatalog: "Catalogue de Services",
    dashboard: "Tableau de Bord",
    catalogServices: "Services du Catalogue",
    orders: "Commandes",
    userDirectory: "Annuaire Utilisateurs",
    exitAdmin: "Quitter Mode Admin",
    switchToAdmin: "Passer en Admin",
    management: "Gestion",
    main: "Principal",
    categories: "Catégories",
    welcomeBack: "Bon retour",
    access: "Accéder",
    logOut: "Déconnexion",
    enterEmail: "Entrez votre email pour accéder à votre tableau de bord.",
    noOrders: "Aucune commande trouvée",
    description: "Description",
    conditions: "Conditions",
    requirements: "Prérequis",
    pricePerUnit: "par unité",
    active: "Actif",
    inactive: "Inactif",
    price: "Prix",
    service: "Service",
    customer: "Client",
    status: "Statut",
    date: "Date",
    actions: "Actions",
    newest: "Plus récents",
    popularity: "Popularité",
    nameAz: "Nom: A - Z",
    globalSearch: "Résultats de Recherche Globale",
    searchResults: "Résultats de Recherche",
    searching: "Recherche",
    showingResults: "Résultats pour",
    tryAdjusting: "Essayez d'ajuster vos filtres ou votre recherche.",
    login: "Connexion",
    register: "Inscription",
    password: "Mot de passe",
    name: "Nom Complet",
    confirmPassword: "Confirmer le mot de passe",
    alreadyAccount: "Déjà un compte ?",
    noAccount: "Pas encore de compte ?",
    profile: "Profil",
    updateProfile: "Mettre à jour le profil",
    loginToAccess: "Connectez-vous pour accéder aux fonctionnalités",
    guestMode: "Mode Invité",
    admin: "Admin",
    user: "Utilisateur",
    accountType: "Type de compte",
    saveChanges: "Enregistrer",
    cancel: "Annuler",
    invalidCredentials: "Email ou mot de passe invalide",
    emailExists: "Email déjà enregistré",
    passwordsDoNotMatch: "Les mots de passe ne correspondent pas",
    accountCreated: "Compte créé avec succès",
    loginSuccess: "Connexion réussie",
    profileUpdated: "Profil mis à jour avec succès",
    role: "Rôle",
    reviews: "Avis",
    writeReview: "Écrire un avis",
    rating: "Note",
    comment: "Commentaire",
    submitReview: "Soumettre",
    noReviews: "Aucun avis pour le moment. Soyez le premier !",
    loginToReview: "Veuillez vous connecter pour laisser un avis.",
    favorites: "Favoris",
    myFavorites: "Mes Favoris",
    reviewAdded: "Avis soumis avec succès",
    loginGoogle: "Continuer avec Google",
    or: "ou",
    settings: "Paramètres",
    general: "Général",
    appearance: "Apparence",
    language: "Langue",
    account: "Compte",
    notifications: "Notifications",
    security: "Sécurité",
    about: "À propos",
    themeLight: "Clair",
    themeDark: "Sombre",
    enableNotifs: "Activer les notifications",
    marketing: "Emails Marketing",
    appVersion: "Version de l'application",
    themeDesc: "Personnalisez l'apparence",
    langDesc: "Choisissez votre langue préférée",
    notifDesc: "Gérez vos préférences de communication"
  },
  ar: {
    searchPlaceholder: "البحث عن الخدمات...",
    searchCategoryPlaceholder: "البحث في هذه الفئة...",
    searchAll: "البحث في جميع الخدمات...",
    filters: "تصنيفات",
    sortBy: "ترتيب حسب",
    priceRange: "نطاق السعر",
    searchScope: "نطاق البحث",
    searchAllCategories: "جميع الفئات",
    heroTitle: "مرحبًا بكم في ATLASVAULT",
    heroSubtitle: "خدمات رقمية متميزة",
    heroDesc: "اكتشف حلول النخبة المصممة لنمط الحياة الرقمي الحديث. من التخزين الآمن إلى الاتصال العالمي والألعاب، نختار الأفضل لك.",
    browseCatalog: "تصفح الكتالوج",
    viewAll: "عرض الكل",
    noServices: "لم يتم العثور على خدمات مطابقة لمعاييرك.",
    startOrder: "ابدأ طلبك",
    email: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    details: "المعرف المطلوب / التفاصيل",
    orderWhatsApp: "اطلب عبر واتساب",
    similarServices: "خدمات مماثلة",
    home: "الرئيسية",
    myOrders: "طلباتي",
    contactSales: "الاتصال بالمبيعات",
    customSolutions: "حلول مخصصة؟",
    customSolutionsDesc: "اتصل بالمبيعات لباقات الشركات.",
    adminConsole: "وحدة تحكم المشرف",
    serviceCatalog: "كتالوج الخدمات",
    dashboard: "لوحة التحكم",
    catalogServices: "خدمات الكتالوج",
    orders: "الطلبات",
    userDirectory: "دليل المستخدمين",
    exitAdmin: "خروج من وضع المشرف",
    switchToAdmin: "التبديل إلى المشرف",
    management: "إدارة",
    main: "رئيسي",
    categories: "الفئات",
    welcomeBack: "مرحبًا بعودتك",
    access: "دخول",
    logOut: "تسجيل الخروج",
    enterEmail: "أدخل بريدك الإلكتروني للوصول إلى لوحة تحكم طلباتك.",
    noOrders: "لم يتم العثور على طلبات",
    description: "الوصف",
    conditions: "الشروط",
    requirements: "المتطلبات",
    pricePerUnit: "للوحدة",
    active: "نشط",
    inactive: "غير نشط",
    price: "السعر",
    service: "الخدمة",
    customer: "العميل",
    status: "الحالة",
    date: "التاريخ",
    actions: "إجراءات",
    newest: "الأحدث",
    popularity: "الأكثر شعبية",
    nameAz: "الاسم: أ - ي",
    globalSearch: "نتائج البحث الشامل",
    searchResults: "نتائج البحث",
    searching: "جاري البحث",
    showingResults: "إظهار النتائج لـ",
    tryAdjusting: "حاول تعديل الفلاتر أو استعلام البحث.",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    password: "كلمة المرور",
    name: "الاسم الكامل",
    confirmPassword: "تأكيد كلمة المرور",
    alreadyAccount: "هل لديك حساب بالفعل؟",
    noAccount: "ليس لديك حساب؟",
    profile: "الملف الشخصي",
    updateProfile: "تحديث الملف الشخصي",
    loginToAccess: "سجل الدخول للوصول إلى الميزات",
    guestMode: "وضع الزائر",
    admin: "مسؤول",
    user: "مستخدم",
    accountType: "نوع الحساب",
    saveChanges: "حفظ التغييرات",
    cancel: "إلغاء",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    emailExists: "البريد الإلكتروني مسجل بالفعل",
    passwordsDoNotMatch: "كلمات المرور غير متطابقة",
    accountCreated: "تم إنشاء الحساب بنجاح",
    loginSuccess: "تم تسجيل الدخول بنجاح",
    profileUpdated: "تم تحديث الملف الشخصي بنجاح",
    role: "الدور",
    reviews: "المراجعات",
    writeReview: "اكتب مراجعة",
    rating: "التقييم",
    comment: "تعليق",
    submitReview: "إرسال المراجعة",
    noReviews: "لا توجد مراجعات بعد. كن أول من يكتب مراجعة!",
    loginToReview: "الرجاء تسجيل الدخول لترك مراجعة.",
    favorites: "المفضلة",
    myFavorites: "مفضلاتي",
    reviewAdded: "تم إرسال المراجعة بنجاح",
    loginGoogle: "المتابعة باستخدام Google",
    or: "أو",
    settings: "الإعدادات",
    general: "عام",
    appearance: "المظهر",
    language: "اللغة",
    account: "الحساب",
    notifications: "الإشعارات",
    security: "الأمان",
    about: "حول",
    themeLight: "فاتح",
    themeDark: "داكن",
    enableNotifs: "تمكين الإشعارات",
    marketing: "رسائل التسويق",
    appVersion: "نسخة التطبيق",
    themeDesc: "تخصيص المظهر والشعور",
    langDesc: "اختر لغتك المفضلة",
    notifDesc: "إدارة تفضيلات الاتصال الخاصة بك"
  }
};

export const CATEGORIES: CategoryMeta[] = [
  {
    id: ServiceCategory.THE_VAULT,
    label: 'The Vault',
    label_fr: 'Le Coffre-Fort',
    label_ar: 'الخزنة',
    icon: 'Shield',
    color: 'text-emerald-500',
    desc: 'Secure storage, premium access, and exclusive memberships.',
    desc_fr: 'Stockage sécurisé, accès premium et adhésions exclusives.',
    desc_ar: 'تخزين آمن، وصول مميز، وعضويات حصرية.',
    order: 1,
  },
  {
    id: ServiceCategory.TELECOM_HUB,
    label: 'Telecom Hub',
    label_fr: 'Pôle Télécom',
    label_ar: 'مركز الاتصالات',
    icon: 'Smartphone',
    color: 'text-blue-500',
    desc: 'Top-tier connectivity, data plans, and virtual numbers.',
    desc_fr: 'Connectivité de haut niveau, forfaits données et numéros virtuels.',
    desc_ar: 'اتصال من الدرجة الأولى، خطط بيانات، وأرقام افتراضية.',
    order: 2,
  },
  {
    id: ServiceCategory.GAMING_CORNER,
    label: 'Gaming Corner',
    label_fr: 'Coin Gaming',
    label_ar: 'ركن الألعاب',
    icon: 'Gamepad2',
    color: 'text-purple-500',
    desc: 'Credits, skins, boosts, and premium game keys.',
    desc_fr: 'Crédits, skins, boosts et clés de jeu premium.',
    desc_ar: 'أرصدة، مظاهر، تعزيزات، ومفاتيح ألعاب مميزة.',
    order: 3,
  },
  {
    id: ServiceCategory.BUSINESS_SUITE,
    label: 'Business Suite',
    label_fr: 'Suite Business',
    label_ar: 'جناح الأعمال',
    icon: 'Briefcase',
    color: 'text-slate-500',
    desc: 'SaaS licenses, marketing tools, and enterprise solutions.',
    desc_fr: 'Licences SaaS, outils marketing et solutions d\'entreprise.',
    desc_ar: 'تراخيص SaaS، أدوات تسويق، وحلول للمؤسسات.',
    order: 4,
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: '1',
    name: 'Encrypted Cloud Storage 1TB',
    category: ServiceCategory.THE_VAULT,
    description: 'Military-grade encryption for your most sensitive data. Accessible anywhere, anytime, with zero-knowledge privacy architecture.',
    price: 60.00,
    currency: 'TND',
    conditions: 'Subscription renews monthly. No refund after 3 days.',
    requiredInfo: 'Email address, PGP Public Key (Optional)',
    active: true,
    createdAt: Date.now(),
    popularity: 85,
  },
  {
    id: '2',
    name: 'Global eSIM Data Plan',
    category: ServiceCategory.TELECOM_HUB,
    description: 'Stay connected in over 140 countries with high-speed 5G data. No physical SIM required.',
    price: 135.00,
    currency: 'TND',
    conditions: 'Valid for 30 days from activation. Device must be eSIM compatible.',
    requiredInfo: 'Device EID, Email address',
    active: true,
    createdAt: Date.now() - 10000,
    popularity: 92,
  },
  {
    id: '3',
    name: 'Rank Boost - Apex Predator',
    category: ServiceCategory.GAMING_CORNER,
    description: 'Professional boosting service to reach the highest ranks. Streamed live for your assurance.',
    price: 450.00,
    currency: 'TND',
    conditions: 'Account sharing required. 2FA must be temporarily disabled or coordinated.',
    requiredInfo: 'Platform, Username, Current Rank',
    active: true,
    createdAt: Date.now() - 20000,
    popularity: 45,
  },
  {
    id: '4',
    name: 'SEO Audit Pro',
    category: ServiceCategory.BUSINESS_SUITE,
    description: 'Comprehensive analysis of your website visibility, keyword rankings, and technical health.',
    price: 900.00,
    currency: 'TND',
    conditions: 'Report delivered within 5 business days.',
    requiredInfo: 'Website URL, Target Keywords, Competitor URLs',
    active: true,
    createdAt: Date.now() - 30000,
    popularity: 60,
  },
    {
    id: '5',
    name: 'Private VPN Access',
    category: ServiceCategory.THE_VAULT,
    description: 'Anonymous browsing with dedicated IP options. Bypass geo-restrictions effortlessly.',
    price: 30.00,
    currency: 'TND',
    conditions: 'Strict no-logs policy.',
    requiredInfo: 'Desired username',
    active: true,
    createdAt: Date.now() - 40000,
    popularity: 98,
  },
];